name = "Dan Evans"
rol = "Python Developer"
email = "danimal100@outlook.com"
phone = "+1 (213) 352-2795"
birthday = "June 6, 1988"
location = "USA"
avatar = "https://i.imgur.com/em6jmBT.jpeg"
username = "devanssound@gmail.com" # <-- github user name
presentation = """
Hi! 
My name is Dan Evans, I'm an experienced Audiovisual and IT Specialist from Raleigh, North Carolina. 
I enjoy turning complex problems into applications and scripts to solve company workflows.

On the edge of IT and compute technologies, my job is to develop these functional programs fully aware of cybersecurity needs.
Automation is the end goal, but human interaction and communication is the key.
"""
