[[post]]
category = "Design"
title = "Design conferences"
subtitle = "https://medium.com"
datetime = "2024-01-01"
image = "./config/assets/posts/blog-1.jpg"
url = "https://medium.com"

[[post]]
category = "Design"
title = "Design digest"
subtitle = "https://hashnode.com"
datetime = "2024-01-01"
image = "./config/assets/posts/blog-3.jpg"
url = "https://hashnode.com"

[[post]]
category = "Design"
title = "UI & Fonts"
subtitle = "https://dev.to"
datetime = "2023-06-23"
image = "./config/assets/posts/blog-4.jpg"
url = "https://dev.to"
