[[doing]]
title = "PowerShell Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using PowerShell and Python to enhance efficiency and productivity."

[[doing]]
title = "IT & TCP/IP Technologies"
icon = "./config/assets/icons/compass.svg"
text = ""

[[doing]]
title = "Audiovisual Specialist"
icon = "./config/assets/icons/mobile.svg"
text = ""
