############## Education config #################
#################################################
[[education]]
title = "SAE Expression College"
timeline = "2008 — 20011"
description = "Bachelor of Applied Science in Audio Engineering"

[[education]]
title = "Wake Technical Community College"
timeline = "2006 — 2008"
description = "Associates in Arts"

############## Experience config ################
#################################################
[[experience]]
title = "IT Service Desk Technician"
timeline = "2021 — Present"
description = "Falls of Neuse Management LLC"

[[experience]]
title = "Service Desk Analyst SME"
timeline = "2019 — 2021"
description = "Allscripts Healthcare Solutions"

[[experience]]
title = "Technology Support Specialist"
timeline = "2015 — 2019"
description = "Hyatt - Destination Hotels"


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "IT System Admin"
value = "80%"

[[skill]]
title = "PowerShell"
value = "70%"

[[skill]]
title = "Audiovisual"
value = "90%"

[[skill]]
title = "Python"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "100%"

[[language]]
title = "Espanol"
value = "50%"